export const columns = [
  {
    type: 'index',
    label: '序号',
    span: 8,
    width: 55,
    align: 'center',
    fixed: 'left',
    // 添加 index 属性用于渲染序号
    index: true,
  },
  {
    name: 'tickNo',
    label: '票号',
    align: 'center',
    span: 8,
  },
  {
    name: 'passportNo',
    label: '护照号',
    valueType: 'input',
    width: 150,
    align: 'center',
    span: 8,
  },
  {
    name: 'trName',
    label: '姓名',
    align: 'center',
    span: 8,
    width: 180,
  },
  {
    name: 'startVoyNo',
    label: '出发航次',
    align: 'center',
    span: 8,
    width: 100,
  },
  {
    name: 'startDate',
    label: '出发时间',
    align: 'center',
    span: 8,
  },
  {
    name: 'returnVoyNo',
    label: '返回航次',
    align: 'center',
    span: 8,
    width: 100,
  },
  {
    name: 'returnDate',
    label: '返回时间',
    align: 'center',
    span: 8,
  },
  {
    name: 'tickType',
    label: '船票类型',
    align: 'center',
    span: 8,
    width: 100,
  },
  {
    name: 'startSeat',
    label: '出发座位',
    align: 'center',
    span: 8,
    width: 100,
  },
  {
    name: 'state',
    label: '出发状态',
    align: 'center',
    span: 8,
    width: 100,
  },
  {
    name: 'returnSeat',
    label: '返回座位',
    align: 'center',
    span: 8,
    width: 100,
  },
  {
    name: 'state',
    label: '返回状态',
    align: 'center',
    span: 8,
    width: 100,
  },
  {
    name: 'tickCost',
    label: '票价',
    align: 'center',
    span: 8,
    width: 80,
  },
  {
    name: 'identity',
    label: '身份',
    align: 'center',
    span: 8,
    width: 100,
  },
]
