export const columns = [
  {
    type: 'selection',
    span: 8,
    align:'center',
    fixed: 'left',
  },
  {
    type: 'index',
    label: '序号',
    span: 8,
    width: 70,
    align:'center',
    fixed: 'left',
    // 添加 index 属性用于渲染序号
    index: true,
  },
  {
    name: 'passportNo',
    label: '护照号',
    search: true,
    valueType: 'input',
    width: 150,
    align:'center',
    span: 8,
    attrs: {
      placeholder: '请输入',
    },
  },
  {
    name: 'trName',
    label: '姓名',
    align: 'center',
    span: 8,
  },
  {
    name: 'trPinYin',
    label: '英文名',
    align: 'center',
    span: 8,
  },
  {
    name: 'trPhone',
    label: '手机号',
    search: true,
    align: 'center',
    width:120,
    valueType: 'input',
    span: 8,
    attrs: {
      placeholder: '请输入',
    },
  },
  {
    name: 'trTmpPhone',
    label: '临时手机号',
    search: true,
    align: 'center',
    width:120,
    valueType: 'input',
    span: 8,
    attrs: {
      placeholder: '请输入',
    },
  },
  {
    name: 'trSex',
    label: '性别',
    slot: true,
    search: true,
    span: 8,
    align: 'center',
    width:70,
    options: [
      {
        value: 1,
        label: '男',
      },
      {
        value: 0,
        label: '女',
      },
    ],
    valueType: 'select',
  },
  {
    name: 'trBirthday',
    label: '出生日期',
    sorter: true,
    search: true,
    align: 'center',
    width: 120,
    valueType: 'input',
    span: 8,
    attrs: {
      placeholder: '请输入',
    },
  },
  {
    name: 'trBorAdd',
    label: '出生地',
    search: true,
    valueType: 'input',
    align: 'center',
    width: 180,
    span: 8,
    attrs: {
      placeholder: '请输入',
    },
  },
  {
    name: 'trNation',
    label: '国籍',
    search: true,
    valueType: 'input',
    width: 120,
    align: 'center',
    span: 8,
    attrs: {
      placeholder: '请输入',
    },
  },
  {
    name: 'travelName',
    label: '旅行社',
    search: true,
    valueType: 'input',
    align: 'center',
    span: 8,
    attrs: {
      placeholder: '请输入',
    },
  },
  {
    name: 'operation',
    slot: true,
    fixed: 'right',
    label: '操作',
    width: 200,
  },
]
