const nation = [
  {
    label: '热门国家',
    options: [
      { en: 'China', label: '中国', value: '中国' },
      { en: 'Russia', label: '俄罗斯', value: '俄罗斯' },
    ],
  },
  {
    label: '所有国家',
    options: [
      { en: 'Angola', label: '安哥拉', value: '安哥拉' },
      { en: 'Afghanistan', label: '阿富汗', value: '阿富汗' },
      { en: 'Albania', label: '阿尔巴尼亚', value: '阿尔巴尼亚' },
      { en: 'Algeria', label: '阿尔及利亚', value: '阿尔及利亚' },
      { en: 'Andorra', label: '安道尔共和国', value: '安道尔共和国' },
      { en: 'Anguilla', label: '安圭拉岛', value: '安圭拉岛' },
      { en: 'Antigua and Barbuda', label: '安提瓜和巴布达', value: '安提瓜和巴布达' },
      { en: 'Argentina', label: '阿根廷', value: '阿根廷' },
      { en: 'Armenia', label: '亚美尼亚', value: '亚美尼亚' },
      { en: 'Ascension', label: '阿森松', value: '阿森松' },
      { en: 'Australia', label: '澳大利亚', value: '澳大利亚' },
      { en: 'Austria', label: '奥地利', value: '奥地利' },
      { en: 'Azerbaijan', label: '阿塞拜疆', value: '阿塞拜疆' },
      { en: 'Bahamas', label: '巴哈马', value: '巴哈马' },
      { en: 'Bahrain', label: '巴林', value: '巴林' },
      { en: 'Bangladesh', label: '孟加拉国', value: '孟加拉国' },
      { en: 'Barbados', label: '巴巴多斯', value: '巴巴多斯' },
      { en: 'Belarus', label: '白俄罗斯', value: '白俄罗斯' },
      { en: 'Belgium', label: '比利时', value: '比利时' },
      { en: 'Belize', label: '伯利兹', value: '伯利兹' },
      { en: 'Benin', label: '贝宁', value: '贝宁' },
      { en: 'Bermuda Is', label: '百慕大群岛', value: '百慕大群岛' },
      { en: 'Bolivia', label: '玻利维亚', value: '玻利维亚' },
      { en: 'Botswana', label: '博茨瓦纳', value: '博茨瓦纳' },
      { en: 'Brazil', label: '巴西', value: '巴西' },
      { en: 'Brunei', label: '文莱', value: '文莱' },
      { en: 'Bulgaria', label: '保加利亚', value: '俄保加利亚罗斯' },
      { en: 'Burkina Faso', label: '布基纳法索', value: '布基纳法索' },
      { en: 'Burma', label: '缅甸', value: '缅甸' },
      { en: 'Burundi', label: '布隆迪', value: '布隆迪' },
      { en: 'Cameroon', label: '喀麦隆', value: '喀麦隆' },
      { en: 'Canada', label: '加拿大', value: '加拿大' },
      { en: 'Cayman Is', label: '开曼群岛', value: '俄罗斯' },
      { en: 'Central African Republic', label: '中非共和国', value: '中非共和国' },
      { en: 'Chad', label: '乍得', value: '乍得' },
      { en: 'Chile', label: '智利', value: '智利' },
      { en: 'China', label: '中国', value: '中国' },
      { en: 'Colombia', label: '哥伦比亚', value: '哥伦比亚' },
      { en: 'Congo', label: '刚果', value: '刚果' },
      { en: 'Cook Is', label: '库克群岛', value: '库克群岛' },
      { en: 'Costa Rica', label: '哥斯达黎加', value: '哥斯达黎加' },
      { en: 'Cuba', label: '古巴', value: '古巴' },
      { en: 'Cyprus', label: '塞浦路斯', value: '塞浦路斯' },
      { en: 'Czech Republic', label: '捷克', value: '捷克' },
      { en: 'Denmark', label: '丹麦', value: '丹麦' },
      { en: 'Djibouti', label: '吉布提', value: '吉布提' },
      { en: 'Dominica Rep', label: '多米尼加共和国', value: '多米尼加共和国' },
      { en: 'Ecuador', label: '厄瓜多尔', value: '厄瓜多尔' },
      { en: 'Egypt', label: '埃及', value: '埃及' },
      { en: 'EI Salvador', label: '萨尔瓦多', value: '萨尔瓦多' },
      { en: 'Estonia', label: '爱沙尼亚', value: '爱沙尼亚' },
      { en: 'Ethiopia', label: '埃塞俄比亚', value: '埃塞俄比亚' },
      { en: 'Fiji', label: '斐济', value: '斐济' },
      { en: 'Finland', label: '芬兰', value: '芬兰' },
      { en: 'France', label: '法国', value: '法国' },
      { en: 'French Guiana', label: '法属圭亚那', value: '法属圭亚那' },
      { en: 'French Polynesia', label: '法属玻利尼西亚', value: '法属玻利尼西亚' },
      { en: 'Gabon', label: '加蓬', value: '加蓬' },
      { en: 'Gambia', label: '冈比亚', value: '冈比亚' },
      { en: 'Georgia', label: '格鲁吉亚', value: '格鲁吉亚' },
      { en: 'Germany', label: '德国', value: '德国' },
      { en: 'Ghana', label: '加纳', value: '加纳' },
      { en: 'Gibraltar', label: '直布罗陀', value: '直布罗陀' },
      { en: 'Greece', label: '希腊', value: '希腊' },
      { en: 'Grenada', label: '格林纳达', value: '格林纳达' },
      { en: 'Guam', label: '关岛', value: '关岛' },
      { en: 'Guatemala', label: '危地马拉', value: '危地马拉' },
      { en: 'Guinea', label: '几内亚', value: '几内亚' },
      { en: 'Guyana', label: '圭亚那', value: '圭亚那' },
      { en: 'Haiti', label: '海地', value: '海地' },
      { en: 'Honduras', label: '洪都拉斯', value: '洪都拉斯' },
      { en: 'Hungary', label: '匈牙利', value: '匈牙利' },
      { en: 'Iceland', label: '冰岛', value: '冰岛' },
      { en: 'India', label: '印度', value: '印度' },
      { en: 'Indonesia', label: '印度尼西亚', value: '印度尼西亚' },
      { en: 'Iran', label: '伊朗', value: '伊朗' },
      { en: 'Iraq', label: '伊拉克', value: '伊拉克' },
      { en: 'Ireland', label: '爱尔兰', value: '爱尔兰' },
      { en: 'Israel', label: '以色列', value: '以色列' },
      { en: 'Italy', label: '意大利', value: '意大利' },
      { en: 'Ivory Coast', label: '科特迪瓦', value: '科特迪瓦' },
      { en: 'Jamaica', label: '牙买加', value: '牙买加' },
      { en: 'Japan', label: '日本', value: '日本' },
      { en: 'Jordan', label: '约旦', value: '约旦' },
      { en: 'Kampuchea (Cambodia )', label: '柬埔寨', value: '柬埔寨' },
      { en: 'Kazakstan', label: '哈萨克斯坦', value: '哈萨克斯坦' },
      { en: 'Kenya', label: '肯尼亚', value: '肯尼亚' },
      { en: 'Korea', label: '韩国', value: '韩国' },
      { en: 'Kuwait', label: '科威特', value: '科威特' },
      { en: 'Kyrgyzstan', label: '吉尔吉斯坦', value: '吉尔吉斯坦' },
      { en: 'Laos', label: '老挝', value: '老挝' },
      { en: 'Latvia', label: '拉脱维亚', value: '拉脱维亚' },
      { en: 'Lebanon', label: '黎巴嫩', value: '黎巴嫩' },
      { en: 'Lesotho', label: '莱索托', value: '莱索托' },
      { en: 'Liberia', label: '利比里亚', value: '利比里亚' },
      { en: 'Libya', label: '利比亚', value: '利比亚' },
      { en: 'Liechtenstein', label: '列支敦士登', value: '列支敦士登' },
      { en: 'Lithuania', label: '立陶宛', value: '立陶宛' },
      { en: 'Luxembourg', label: '卢森堡', value: '卢森堡' },
      { en: 'Madagascar', label: '马达加斯加', value: '马达加斯加' },
      { en: 'Malawi', label: '马拉维', value: '马拉维' },
      { en: 'Malaysia', label: '马来西亚', value: '马来西亚' },
      { en: 'Maldives', label: '马尔代夫', value: '马尔代夫' },
      { en: 'Mali', label: '马里', value: '马里' },
      { en: 'Malta', label: '马耳他', value: '马耳他' },
      { en: 'Mariana Is', label: '马里亚那群岛', value: '马里亚那群岛' },
      { en: 'Martinique', label: '马提尼克', value: '马提尼克' },
      { en: 'Mauritius', label: '毛里求斯', value: '毛里求斯' },
      { en: 'Mexico', label: '墨西哥', value: '墨西哥' },
      { en: 'Moldova', label: '摩尔多瓦', value: '摩尔多瓦' },
      { en: 'Monaco', label: '摩纳哥', value: '摩纳哥' },
      { en: 'Mongolia', label: '蒙古', value: '蒙古' },
      { en: 'Montserrat Is', label: '蒙特塞拉特岛', value: '蒙特塞拉特岛' },
      { en: 'Morocco', label: '摩洛哥', value: '摩洛哥' },
      { en: 'Mozambique', label: '莫桑比克', value: '莫桑比克' },
      { en: 'Namibia', label: '纳米比亚', value: '纳米比亚' },
      { en: 'Nauru', label: '瑙鲁', value: '瑙鲁' },
      { en: 'Nepal', label: '尼泊尔', value: '尼泊尔' },
      { en: 'Netheriands Antilles', label: '荷属安的列斯', value: '荷属安的列斯' },
      { en: 'Netherlands', label: '荷兰', value: '荷兰' },
      { en: 'New Zealand', label: '新西兰', value: '新西兰' },
      { en: 'Nicaragua', label: '尼加拉瓜', value: '尼加拉瓜' },
      { en: 'Niger', label: '尼日尔', value: '尼日尔' },
      { en: 'Nigeria', label: '尼日利亚', value: '尼日利亚' },
      { en: 'North Korea', label: '朝鲜', value: '朝鲜' },
      { en: 'Norway', label: '挪威', value: '挪威' },
      { en: 'Oman', label: '阿曼', value: '阿曼' },
      { en: 'Pakistan', label: '巴基斯坦', value: '巴基斯坦' },
      { en: 'Panama', label: '巴拿马', value: '巴拿马' },
      { en: 'Papua New Cuinea', label: '巴布亚新几内亚', value: '巴布亚新几内亚' },
      { en: 'Paraguay', label: '巴拉圭', value: '巴拉圭' },
      { en: 'Peru', label: '秘鲁', value: '秘鲁' },
      { en: 'Philippines', label: '菲律宾', value: '菲律宾' },
      { en: 'Poland', label: '波兰', value: '波兰' },
      { en: 'Portugal', label: '葡萄牙', value: '葡萄牙' },
      { en: 'Puerto Rico', label: '波多黎各', value: '波多黎各' },
      { en: 'Qatar', label: '卡塔尔', value: '卡塔尔' },
      { en: 'Reunion', label: '留尼旺', value: '留尼旺' },
      { en: 'Romania', label: '罗马尼亚', value: '罗马尼亚' },
      { en: 'Russia', label: '俄罗斯', value: '俄罗斯' },
      { en: 'Saint Lueia', label: '圣卢西亚', value: '圣卢西亚' },
      { en: 'Saint Vincent', label: '圣文森特岛', value: '圣文森特岛' },
      { en: 'Samoa Eastern', label: '东萨摩亚(美)', value: '东萨摩亚(美)' },
      { en: 'Samoa Western', label: '西萨摩亚', value: '西萨摩亚' },
      { en: 'San Marino', label: '圣马力诺', value: '圣马力诺' },
      { en: 'Sao Tome and Principe', label: '圣多美和普林西比', value: '圣多美和普林西比' },
      { en: 'Saudi Arabia', label: '沙特阿拉伯', value: '沙特阿拉伯' },
      { en: 'Senegal', label: '塞内加尔', value: '塞内加尔' },
      { en: 'Seychelles', label: '塞舌尔', value: '塞舌尔' },
      { en: 'Sierra Leone', label: '塞拉利昂', value: '塞拉利昂' },
      { en: 'Singapore', label: '新加坡', value: '新加坡' },
      { en: 'Slovakia', label: '斯洛伐克', value: '斯洛伐克' },
      { en: 'Slovenia', label: '斯洛文尼亚', value: '斯洛文尼亚' },
      { en: 'Solomon Is', label: '所罗门群岛', value: '所罗门群岛' },
      { en: 'Somali', label: '索马里', value: '索马里' },
      { en: 'South Africa', label: '南非', value: '南非' },
      { en: 'Spain', label: '西班牙', value: '西班牙' },
      { en: 'SriLanka', label: '斯里兰卡', value: '斯里兰卡' },
      { en: 'St.Lucia', label: '圣卢西亚', value: '圣卢西亚' },
      { en: 'St.Vincent', label: '圣文森特', value: '圣文森特' },
      { en: 'Sudan', label: '苏丹', value: '苏丹' },
      { en: 'Suriname', label: '苏里南', value: '苏里南' },
      { en: 'Swaziland', label: '斯威士兰', value: '斯威士兰' },
      { en: 'Sweden', label: '瑞典', value: '瑞典' },
      { en: 'Switzerland', label: '瑞士', value: '瑞士' },
      { en: 'Syria', label: '叙利亚', value: '叙利亚' },
      { en: 'Tajikstan', label: '塔吉克斯坦', value: '塔吉克斯坦' },
      { en: 'Tanzania', label: '坦桑尼亚', value: '坦桑尼亚' },
      { en: 'Thailand', label: '泰国', value: '泰国' },
      { en: 'Togo', label: '多哥', value: '多哥' },
      { en: 'Tonga', label: '汤加', value: '汤加' },
      { en: 'Trinidad and Tobago', label: '特立尼达和多巴哥', value: '特立尼达和多巴哥' },
      { en: 'Tunisia', label: '突尼斯', value: '突尼斯' },
      { en: 'Turkey', label: '土耳其', value: '土耳其' },
      { en: 'Turkmenistan', label: '土库曼斯坦', value: '土库曼斯坦' },
      { en: 'Uganda', label: '乌干达', value: '乌干达' },
      { en: 'Ukraine', label: '乌克兰', value: '乌克兰' },
      { en: 'United Arab Emirates', label: '阿拉伯联合酋长国', value: '阿拉伯联合酋长国' },
      { en: 'United Kiongdom', label: '英国', value: '英国' },
      { en: 'United States of America', label: '美国', value: '美国' },
      { en: 'Uruguay', label: '乌拉圭', value: '乌拉圭' },
      { en: 'Uzbekistan', label: '乌兹别克斯坦', value: '乌兹别克斯坦' },
      { en: 'Venezuela', label: '委内瑞拉', value: '委内瑞拉' },
      { en: 'Vietnam', label: '越南', value: '越南' },
      { en: 'Yemen', label: '也门', value: '也门' },
      { en: 'Yugoslavia', label: '南斯拉夫', value: '南斯拉夫' },
      { en: 'Zimbabwe', label: '津巴布韦', value: '津巴布韦' },
      { en: 'Zaire', label: '扎伊尔', value: '扎伊尔' },
      { en: 'Zambia', label: '赞比亚', value: '赞比亚' },
    ],
  },
]

export default nation
